<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/audit/', 'middleware' => 'admin','as'=>'admin.audit.'), function () {

Route::get('reffActivities', ['as'=> 'reffActivities.index', 'uses' => 'Audit\ReffActivityController@index']);
Route::post('reffActivities', ['as'=> 'reffActivities.store', 'uses' => 'Audit\ReffActivityController@store']);
Route::get('reffActivities/create', ['as'=> 'reffActivities.create', 'uses' => 'Audit\ReffActivityController@create']);
Route::put('reffActivities/{reffActivities}', ['as'=> 'reffActivities.update', 'uses' => 'Audit\ReffActivityController@update']);
Route::patch('reffActivities/{reffActivities}', ['as'=> 'reffActivities.update', 'uses' => 'Audit\ReffActivityController@update']);
Route::get('reffActivities/{id}/delete', array('as' => 'reffActivities.delete', 'uses' => 'Audit\ReffActivityController@getDelete'));
Route::get('reffActivities/{id}/confirm-delete', array('as' => 'reffActivities.confirm-delete', 'uses' => 'Audit\ReffActivityController@getModalDelete'));
Route::get('reffActivities/{reffActivities}', ['as'=> 'reffActivities.show', 'uses' => 'Audit\ReffActivityController@show']);
Route::get('reffActivities/{reffActivities}/edit', ['as'=> 'reffActivities.edit', 'uses' => 'Audit\ReffActivityController@edit']);

});


Route::group(array('prefix' => 'admin/audit/', 'middleware' => 'admin','as'=>'admin.audit.'), function () {

Route::get('reffActivities', ['as'=> 'reffActivities.index', 'uses' => 'Audit\ReffActivityController@index']);
Route::post('reffActivities', ['as'=> 'reffActivities.store', 'uses' => 'Audit\ReffActivityController@store']);
Route::get('reffActivities/create', ['as'=> 'reffActivities.create', 'uses' => 'Audit\ReffActivityController@create']);
Route::put('reffActivities/{reffActivities}', ['as'=> 'reffActivities.update', 'uses' => 'Audit\ReffActivityController@update']);
Route::patch('reffActivities/{reffActivities}', ['as'=> 'reffActivities.update', 'uses' => 'Audit\ReffActivityController@update']);
Route::get('reffActivities/{id}/delete', array('as' => 'reffActivities.delete', 'uses' => 'Audit\ReffActivityController@getDelete'));
Route::get('reffActivities/{id}/confirm-delete', array('as' => 'reffActivities.confirm-delete', 'uses' => 'Audit\ReffActivityController@getModalDelete'));
Route::get('reffActivities/{reffActivities}', ['as'=> 'reffActivities.show', 'uses' => 'Audit\ReffActivityController@show']);
Route::get('reffActivities/{reffActivities}/edit', ['as'=> 'reffActivities.edit', 'uses' => 'Audit\ReffActivityController@edit']);

});


Route::group(array('prefix' => 'admin/audit/', 'middleware' => 'admin','as'=>'admin.audit.'), function () {

Route::get('reffActivities', ['as'=> 'reffActivities.index', 'uses' => 'Audit\ReffActivityController@index']);
Route::post('reffActivities', ['as'=> 'reffActivities.store', 'uses' => 'Audit\ReffActivityController@store']);
Route::get('reffActivities/create', ['as'=> 'reffActivities.create', 'uses' => 'Audit\ReffActivityController@create']);
Route::put('reffActivities/{reffActivities}', ['as'=> 'reffActivities.update', 'uses' => 'Audit\ReffActivityController@update']);
Route::patch('reffActivities/{reffActivities}', ['as'=> 'reffActivities.update', 'uses' => 'Audit\ReffActivityController@update']);
Route::get('reffActivities/{id}/delete', array('as' => 'reffActivities.delete', 'uses' => 'Audit\ReffActivityController@getDelete'));
Route::get('reffActivities/{id}/confirm-delete', array('as' => 'reffActivities.confirm-delete', 'uses' => 'Audit\ReffActivityController@getModalDelete'));
Route::get('reffActivities/{reffActivities}', ['as'=> 'reffActivities.show', 'uses' => 'Audit\ReffActivityController@show']);
Route::get('reffActivities/{reffActivities}/edit', ['as'=> 'reffActivities.edit', 'uses' => 'Audit\ReffActivityController@edit']);

});


Route::group(array('prefix' => 'admin/audit/', 'middleware' => 'admin','as'=>'admin.audit.'), function () {

Route::get('reffActivities', ['as'=> 'reffActivities.index', 'uses' => 'Audit\ReffActivityController@index']);
Route::post('reffActivities', ['as'=> 'reffActivities.store', 'uses' => 'Audit\ReffActivityController@store']);
Route::get('reffActivities/create', ['as'=> 'reffActivities.create', 'uses' => 'Audit\ReffActivityController@create']);
Route::put('reffActivities/{reffActivities}', ['as'=> 'reffActivities.update', 'uses' => 'Audit\ReffActivityController@update']);
Route::patch('reffActivities/{reffActivities}', ['as'=> 'reffActivities.update', 'uses' => 'Audit\ReffActivityController@update']);
Route::get('reffActivities/{id}/delete', array('as' => 'reffActivities.delete', 'uses' => 'Audit\ReffActivityController@getDelete'));
Route::get('reffActivities/{id}/confirm-delete', array('as' => 'reffActivities.confirm-delete', 'uses' => 'Audit\ReffActivityController@getModalDelete'));
Route::get('reffActivities/{reffActivities}', ['as'=> 'reffActivities.show', 'uses' => 'Audit\ReffActivityController@show']);
Route::get('reffActivities/{reffActivities}/edit', ['as'=> 'reffActivities.edit', 'uses' => 'Audit\ReffActivityController@edit']);

});


Route::group(array('prefix' => 'admin/audit/', 'middleware' => 'admin','as'=>'admin.audit.'), function () {

Route::get('reffClassAudits', ['as'=> 'reffClassAudits.index', 'uses' => 'Audit\ReffClassAuditController@index']);
Route::post('reffClassAudits', ['as'=> 'reffClassAudits.store', 'uses' => 'Audit\ReffClassAuditController@store']);
Route::get('reffClassAudits/create', ['as'=> 'reffClassAudits.create', 'uses' => 'Audit\ReffClassAuditController@create']);
Route::put('reffClassAudits/{reffClassAudits}', ['as'=> 'reffClassAudits.update', 'uses' => 'Audit\ReffClassAuditController@update']);
Route::patch('reffClassAudits/{reffClassAudits}', ['as'=> 'reffClassAudits.update', 'uses' => 'Audit\ReffClassAuditController@update']);
Route::get('reffClassAudits/{id}/delete', array('as' => 'reffClassAudits.delete', 'uses' => 'Audit\ReffClassAuditController@getDelete'));
Route::get('reffClassAudits/{id}/confirm-delete', array('as' => 'reffClassAudits.confirm-delete', 'uses' => 'Audit\ReffClassAuditController@getModalDelete'));
Route::get('reffClassAudits/{reffClassAudits}', ['as'=> 'reffClassAudits.show', 'uses' => 'Audit\ReffClassAuditController@show']);
Route::get('reffClassAudits/{reffClassAudits}/edit', ['as'=> 'reffClassAudits.edit', 'uses' => 'Audit\ReffClassAuditController@edit']);

});
